# coding: utf-8

"""
    Soroban Pulse API

    Indexes Soroban smart contract events on the Stellar network.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.contract_summary import ContractSummary

class TestContractSummary(unittest.TestCase):
    """ContractSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractSummary:
        """Test ContractSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractSummary`
        """
        model = ContractSummary()
        if include_optional:
            return ContractSummary(
                contract_id = '',
                event_count = 56,
                latest_ledger = 56
            )
        else:
            return ContractSummary(
                contract_id = '',
                event_count = 56,
                latest_ledger = 56,
        )
        """

    def testContractSummary(self):
        """Test ContractSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
