# coding: utf-8

"""
    Soroban Pulse API

    Indexes Soroban smart contract events on the Stellar network.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.events_api import EventsApi


class TestEventsApi(unittest.IsolatedAsyncioTestCase):
    """EventsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = EventsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_contracts(self) -> None:
        """Test case for get_contracts

        """
        pass

    async def test_get_events(self) -> None:
        """Test case for get_events

        """
        pass

    async def test_get_events_by_contract(self) -> None:
        """Test case for get_events_by_contract

        """
        pass

    async def test_get_events_by_tx(self) -> None:
        """Test case for get_events_by_tx

        """
        pass

    async def test_stream_events(self) -> None:
        """Test case for stream_events

        Stream new events in real time via Server-Sent Events.
        """
        pass

    async def test_stream_events_by_contract(self) -> None:
        """Test case for stream_events_by_contract

        Stream new events for a specific contract in real time via Server-Sent Events.
        """
        pass


if __name__ == '__main__':
    unittest.main()
