# coding: utf-8

"""
    Soroban Pulse API

    Indexes Soroban smart contract events on the Stellar network.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pagination_params import PaginationParams

class TestPaginationParams(unittest.TestCase):
    """PaginationParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginationParams:
        """Test PaginationParams
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginationParams`
        """
        model = PaginationParams()
        if include_optional:
            return PaginationParams(
                cursor = '',
                event_type = 'contract',
                exact_count = True,
                fields = '',
                from_ledger = 56,
                limit = 56,
                page = 56,
                to_ledger = 56
            )
        else:
            return PaginationParams(
        )
        """

    def testPaginationParams(self):
        """Test PaginationParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
