# coding: utf-8

"""
    Soroban Pulse API

    Indexes Soroban smart contract events on the Stellar network.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.system_api import SystemApi


class TestSystemApi(unittest.IsolatedAsyncioTestCase):
    """SystemApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SystemApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_health(self) -> None:
        """Test case for health

        """
        pass

    async def test_status(self) -> None:
        """Test case for status

        """
        pass


if __name__ == '__main__':
    unittest.main()
