/* tslint:disable */
/* eslint-disable */
/**
 * Soroban Pulse API
 * Indexes Soroban smart contract events on the Stellar network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractSummary
 */
export interface ContractSummary {
    /**
     * 
     * @type {string}
     * @memberof ContractSummary
     */
    contractId: string;
    /**
     * 
     * @type {number}
     * @memberof ContractSummary
     */
    eventCount: number;
    /**
     * 
     * @type {number}
     * @memberof ContractSummary
     */
    latestLedger: number;
}

/**
 * Check if a given object implements the ContractSummary interface.
 */
export function instanceOfContractSummary(value: object): value is ContractSummary {
    if (!('contractId' in value) || value['contractId'] === undefined) return false;
    if (!('eventCount' in value) || value['eventCount'] === undefined) return false;
    if (!('latestLedger' in value) || value['latestLedger'] === undefined) return false;
    return true;
}

export function ContractSummaryFromJSON(json: any): ContractSummary {
    return ContractSummaryFromJSONTyped(json, false);
}

export function ContractSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'contractId': json['contract_id'],
        'eventCount': json['event_count'],
        'latestLedger': json['latest_ledger'],
    };
}

export function ContractSummaryToJSON(json: any): ContractSummary {
    return ContractSummaryToJSONTyped(json, false);
}

export function ContractSummaryToJSONTyped(value?: ContractSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contract_id': value['contractId'],
        'event_count': value['eventCount'],
        'latest_ledger': value['latestLedger'],
    };
}

