/* tslint:disable */
/* eslint-disable */
/**
 * Soroban Pulse API
 * Indexes Soroban smart contract events on the Stellar network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventType } from './EventType';
import {
    EventTypeFromJSON,
    EventTypeFromJSONTyped,
    EventTypeToJSON,
    EventTypeToJSONTyped,
} from './EventType';

/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    contractId: string;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    createdAt: Date;
    /**
     * 
     * @type {any}
     * @memberof Event
     */
    eventData: any | null;
    /**
     * 
     * @type {EventType}
     * @memberof Event
     */
    eventType: EventType;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof Event
     */
    ledger: number;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    txHash: string;
}



/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): value is Event {
    if (!('contractId' in value) || value['contractId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('eventData' in value) || value['eventData'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ledger' in value) || value['ledger'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('txHash' in value) || value['txHash'] === undefined) return false;
    return true;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if (json == null) {
        return json;
    }
    return {
        
        'contractId': json['contract_id'],
        'createdAt': (new Date(json['created_at'])),
        'eventData': json['event_data'],
        'eventType': EventTypeFromJSON(json['event_type']),
        'id': json['id'],
        'ledger': json['ledger'],
        'timestamp': (new Date(json['timestamp'])),
        'txHash': json['tx_hash'],
    };
}

export function EventToJSON(json: any): Event {
    return EventToJSONTyped(json, false);
}

export function EventToJSONTyped(value?: Event | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contract_id': value['contractId'],
        'created_at': value['createdAt'].toISOString(),
        'event_data': value['eventData'],
        'event_type': EventTypeToJSON(value['eventType']),
        'id': value['id'],
        'ledger': value['ledger'],
        'timestamp': value['timestamp'].toISOString(),
        'tx_hash': value['txHash'],
    };
}

