/* tslint:disable */
/* eslint-disable */
/**
 * Soroban Pulse API
 * Indexes Soroban smart contract events on the Stellar network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventType } from './EventType';
import {
    EventTypeFromJSON,
    EventTypeFromJSONTyped,
    EventTypeToJSON,
    EventTypeToJSONTyped,
} from './EventType';

/**
 * 
 * @export
 * @interface PaginationParams
 */
export interface PaginationParams {
    /**
     * 
     * @type {string}
     * @memberof PaginationParams
     */
    cursor?: string | null;
    /**
     * 
     * @type {EventType}
     * @memberof PaginationParams
     */
    eventType?: EventType | null;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationParams
     */
    exactCount?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof PaginationParams
     */
    fields?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationParams
     */
    fromLedger?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationParams
     */
    limit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationParams
     */
    page?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationParams
     */
    toLedger?: number | null;
}



/**
 * Check if a given object implements the PaginationParams interface.
 */
export function instanceOfPaginationParams(value: object): value is PaginationParams {
    return true;
}

export function PaginationParamsFromJSON(json: any): PaginationParams {
    return PaginationParamsFromJSONTyped(json, false);
}

export function PaginationParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationParams {
    if (json == null) {
        return json;
    }
    return {
        
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'eventType': json['event_type'] == null ? undefined : EventTypeFromJSON(json['event_type']),
        'exactCount': json['exact_count'] == null ? undefined : json['exact_count'],
        'fields': json['fields'] == null ? undefined : json['fields'],
        'fromLedger': json['from_ledger'] == null ? undefined : json['from_ledger'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'page': json['page'] == null ? undefined : json['page'],
        'toLedger': json['to_ledger'] == null ? undefined : json['to_ledger'],
    };
}

export function PaginationParamsToJSON(json: any): PaginationParams {
    return PaginationParamsToJSONTyped(json, false);
}

export function PaginationParamsToJSONTyped(value?: PaginationParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cursor': value['cursor'],
        'event_type': EventTypeToJSON(value['eventType']),
        'exact_count': value['exactCount'],
        'fields': value['fields'],
        'from_ledger': value['fromLedger'],
        'limit': value['limit'],
        'page': value['page'],
        'to_ledger': value['toLedger'],
    };
}

