/* tslint:disable */
/* eslint-disable */
/**
 * Soroban Pulse API
 * Indexes Soroban smart contract events on the Stellar network.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EventType,
} from '../models/index';
import {
    EventTypeFromJSON,
    EventTypeToJSON,
} from '../models/index';

export interface GetContractsRequest {
    page?: number | null;
    limit?: number | null;
}

export interface GetEventsRequest {
    page?: number | null;
    limit?: number | null;
    exactCount?: boolean | null;
    eventType?: EventType | null;
    fromLedger?: number | null;
    toLedger?: number | null;
}

export interface GetEventsByContractRequest {
    contractId: string;
    page?: number | null;
    limit?: number | null;
    fromLedger?: number | null;
    toLedger?: number | null;
}

export interface GetEventsByTxRequest {
    txHash: string;
}

export interface StreamEventsRequest {
    contractId?: string | null;
}

export interface StreamEventsByContractRequest {
    contractId: string;
}

/**
 * 
 */
export class EventsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getContracts without sending the request
     */
    async getContractsRequestOpts(requestParameters: GetContractsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/contracts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getContractsRaw(requestParameters: GetContractsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getContractsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async getContracts(requestParameters: GetContractsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getContractsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getEvents without sending the request
     */
    async getEventsRequestOpts(requestParameters: GetEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['exactCount'] != null) {
            queryParameters['exact_count'] = requestParameters['exactCount'];
        }

        if (requestParameters['eventType'] != null) {
            queryParameters['event_type'] = requestParameters['eventType'];
        }

        if (requestParameters['fromLedger'] != null) {
            queryParameters['from_ledger'] = requestParameters['fromLedger'];
        }

        if (requestParameters['toLedger'] != null) {
            queryParameters['to_ledger'] = requestParameters['toLedger'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/events`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getEventsRaw(requestParameters: GetEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async getEvents(requestParameters: GetEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getEventsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getEventsByContract without sending the request
     */
    async getEventsByContractRequestOpts(requestParameters: GetEventsByContractRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contractId'] == null) {
            throw new runtime.RequiredError(
                'contractId',
                'Required parameter "contractId" was null or undefined when calling getEventsByContract().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['fromLedger'] != null) {
            queryParameters['from_ledger'] = requestParameters['fromLedger'];
        }

        if (requestParameters['toLedger'] != null) {
            queryParameters['to_ledger'] = requestParameters['toLedger'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/events/contract/{contract_id}`;
        urlPath = urlPath.replace(`{${"contract_id"}}`, encodeURIComponent(String(requestParameters['contractId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getEventsByContractRaw(requestParameters: GetEventsByContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getEventsByContractRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async getEventsByContract(requestParameters: GetEventsByContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getEventsByContractRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getEventsByTx without sending the request
     */
    async getEventsByTxRequestOpts(requestParameters: GetEventsByTxRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['txHash'] == null) {
            throw new runtime.RequiredError(
                'txHash',
                'Required parameter "txHash" was null or undefined when calling getEventsByTx().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/events/tx/{tx_hash}`;
        urlPath = urlPath.replace(`{${"tx_hash"}}`, encodeURIComponent(String(requestParameters['txHash'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getEventsByTxRaw(requestParameters: GetEventsByTxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getEventsByTxRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async getEventsByTx(requestParameters: GetEventsByTxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getEventsByTxRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for streamEvents without sending the request
     */
    async streamEventsRequestOpts(requestParameters: StreamEventsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['contractId'] != null) {
            queryParameters['contract_id'] = requestParameters['contractId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/events/stream`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * This endpoint is less preferred for contract-specific streaming; use `/v1/events/contract/{contract_id}/stream` instead.
     * Stream new events in real time via Server-Sent Events.
     */
    async streamEventsRaw(requestParameters: StreamEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.streamEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint is less preferred for contract-specific streaming; use `/v1/events/contract/{contract_id}/stream` instead.
     * Stream new events in real time via Server-Sent Events.
     */
    async streamEvents(requestParameters: StreamEventsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.streamEventsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for streamEventsByContract without sending the request
     */
    async streamEventsByContractRequestOpts(requestParameters: StreamEventsByContractRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contractId'] == null) {
            throw new runtime.RequiredError(
                'contractId',
                'Required parameter "contractId" was null or undefined when calling streamEventsByContract().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/events/contract/{contract_id}/stream`;
        urlPath = urlPath.replace(`{${"contract_id"}}`, encodeURIComponent(String(requestParameters['contractId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stream new events for a specific contract in real time via Server-Sent Events.
     */
    async streamEventsByContractRaw(requestParameters: StreamEventsByContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.streamEventsByContractRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stream new events for a specific contract in real time via Server-Sent Events.
     */
    async streamEventsByContract(requestParameters: StreamEventsByContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.streamEventsByContractRaw(requestParameters, initOverrides);
    }

}
