# coding: utf-8

"""
    Soroban Pulse API

    Indexes Soroban smart contract events on the Stellar network.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from openapi_client.models.event_type import EventType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Event(BaseModel):
    """
    Event
    """ # noqa: E501
    contract_id: StrictStr
    created_at: datetime
    event_data: Optional[Any]
    event_type: EventType
    id: UUID
    ledger: StrictInt
    timestamp: datetime
    tx_hash: StrictStr
    __properties: ClassVar[List[str]] = ["contract_id", "created_at", "event_data", "event_type", "id", "ledger", "timestamp", "tx_hash"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Event from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if event_data (nullable) is None
        # and model_fields_set contains the field
        if self.event_data is None and "event_data" in self.model_fields_set:
            _dict['event_data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Event from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "contract_id": obj.get("contract_id"),
            "created_at": obj.get("created_at"),
            "event_data": obj.get("event_data"),
            "event_type": obj.get("event_type"),
            "id": obj.get("id"),
            "ledger": obj.get("ledger"),
            "timestamp": obj.get("timestamp"),
            "tx_hash": obj.get("tx_hash")
        })
        return _obj


