# coding: utf-8

"""
    Soroban Pulse API

    Indexes Soroban smart contract events on the Stellar network.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EventType(str, Enum):
    """
    EventType
    """

    """
    allowed enum values
    """
    CONTRACT = 'contract'
    DIAGNOSTIC = 'diagnostic'
    SYSTEM = 'system'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventType from a JSON string"""
        return cls(json.loads(json_str))


