# coding: utf-8

"""
    Soroban Pulse API

    Indexes Soroban smart contract events on the Stellar network.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.event_type import EventType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PaginationParams(BaseModel):
    """
    PaginationParams
    """ # noqa: E501
    cursor: Optional[StrictStr] = None
    event_type: Optional[EventType] = None
    exact_count: Optional[StrictBool] = None
    fields: Optional[StrictStr] = None
    from_ledger: Optional[StrictInt] = None
    limit: Optional[StrictInt] = None
    page: Optional[StrictInt] = None
    to_ledger: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["cursor", "event_type", "exact_count", "fields", "from_ledger", "limit", "page", "to_ledger"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaginationParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cursor (nullable) is None
        # and model_fields_set contains the field
        if self.cursor is None and "cursor" in self.model_fields_set:
            _dict['cursor'] = None

        # set to None if event_type (nullable) is None
        # and model_fields_set contains the field
        if self.event_type is None and "event_type" in self.model_fields_set:
            _dict['event_type'] = None

        # set to None if exact_count (nullable) is None
        # and model_fields_set contains the field
        if self.exact_count is None and "exact_count" in self.model_fields_set:
            _dict['exact_count'] = None

        # set to None if fields (nullable) is None
        # and model_fields_set contains the field
        if self.fields is None and "fields" in self.model_fields_set:
            _dict['fields'] = None

        # set to None if from_ledger (nullable) is None
        # and model_fields_set contains the field
        if self.from_ledger is None and "from_ledger" in self.model_fields_set:
            _dict['from_ledger'] = None

        # set to None if limit (nullable) is None
        # and model_fields_set contains the field
        if self.limit is None and "limit" in self.model_fields_set:
            _dict['limit'] = None

        # set to None if page (nullable) is None
        # and model_fields_set contains the field
        if self.page is None and "page" in self.model_fields_set:
            _dict['page'] = None

        # set to None if to_ledger (nullable) is None
        # and model_fields_set contains the field
        if self.to_ledger is None and "to_ledger" in self.model_fields_set:
            _dict['to_ledger'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaginationParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cursor": obj.get("cursor"),
            "event_type": obj.get("event_type"),
            "exact_count": obj.get("exact_count"),
            "fields": obj.get("fields"),
            "from_ledger": obj.get("from_ledger"),
            "limit": obj.get("limit"),
            "page": obj.get("page"),
            "to_ledger": obj.get("to_ledger")
        })
        return _obj


